include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for Wireless Setting
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat +luci-lib-jsonc +luci-app-fwx-network +luci-app-fwx-resources +fwxd

PKG_NAME:=luci-app-fwx-wireless
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

