include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for Traffic Statistics
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat +luci-app-fwx-resources

PKG_NAME:=luci-app-fwx-traffic-stat
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
